"""Generate a dependency-minimal standalone plan interpreter."""

from __future__ import annotations

from pathlib import Path

from neuralabi.formats.plan import ConversionPlan, validate_plan
from neuralabi.util.canonical_json import canonical_dumps

_TEMPLATE = r'''#!/usr/bin/env python3
"""Standalone NeuralABI checkpoint converter.

Generated by NeuralABI __TOOL_VERSION__. It contains a declarative, non-executable plan and does
not import source or target model code. Trust the local Python environment, PyTorch, SafeTensors,
and this generated file; checkpoint indexes and metadata are validated as untrusted input.

Plan hash: __PLAN_HASH__
Source graph hash: __SOURCE_GRAPH_HASH__
Target graph hash: __TARGET_GRAPH_HASH__
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import tempfile
from pathlib import Path

import torch
from safetensors import safe_open
from safetensors.torch import save_file

PLAN = json.loads(__PLAN_JSON_LITERAL__)
MAX_INDEX_BYTES = 32 * 1024 * 1024


class ConversionError(Exception):
    pass


def dtype_name(tensor):
    return str(tensor.dtype).removeprefix("torch.")


def metadata(tensor):
    return tuple(int(x) for x in tensor.shape), dtype_name(tensor)


class Store:
    def __init__(self, path):
        path = Path(path).resolve(strict=True)
        self.files = {}
        if path.is_dir():
            indexes = sorted(path.glob("*.safetensors.index.json"))
            singles = sorted(path.glob("*.safetensors"))
            if len(indexes) == 1:
                path = indexes[0]
            elif len(indexes) == 0 and len(singles) == 1:
                path = singles[0]
            else:
                raise ConversionError("checkpoint directory must contain one SafeTensors file or index")
        if path.name.endswith(".safetensors.index.json"):
            if path.stat().st_size > MAX_INDEX_BYTES:
                raise ConversionError("checkpoint index exceeds the size limit")
            try:
                index = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, UnicodeError, json.JSONDecodeError) as exc:
                raise ConversionError(f"invalid checkpoint index: {exc}") from exc
            if not isinstance(index, dict) or set(index) - {"metadata", "weight_map"}:
                raise ConversionError("checkpoint index has unknown fields")
            weight_map = index.get("weight_map")
            if not isinstance(weight_map, dict) or not weight_map:
                raise ConversionError("checkpoint index has no weight map")
            for key, filename in weight_map.items():
                if not isinstance(key, str) or not isinstance(filename, str):
                    raise ConversionError("checkpoint index keys and filenames must be strings")
                candidate = Path(filename)
                if candidate.is_absolute() or candidate.name != filename or filename in {"", ".", ".."}:
                    raise ConversionError(f"unsafe shard filename {filename!r}")
                shard = path.parent / filename
                if not shard.is_file():
                    raise ConversionError(f"missing checkpoint shard {filename!r}")
                self.files[key] = shard
        elif path.suffix == ".safetensors":
            with safe_open(path, framework="pt", device="cpu") as handle:
                self.files = {key: path for key in handle.keys()}
        else:
            raise ConversionError("v0.1 accepts only SafeTensors checkpoints")
        self._keys = tuple(sorted(self.files))
        for filename in sorted(set(self.files.values())):
            with safe_open(filename, framework="pt", device="cpu") as handle:
                actual = set(handle.keys())
            expected = {key for key, owner in self.files.items() if owner == filename}
            if actual != expected:
                raise ConversionError(f"shard/index key disagreement in {filename.name}")

    def keys(self):
        return self._keys

    def read(self, key):
        if key not in self.files:
            raise ConversionError(f"missing source tensor {key!r}")
        with safe_open(self.files[key], framework="pt", device="cpu") as handle:
            return handle.get_tensor(key).clone()


def fingerprint(store):
    digest = hashlib.sha256(b"neuralabi-logical-checkpoint-v1\0")
    for key in store.keys():
        tensor = store.read(key).detach().cpu().contiguous()
        key_bytes = key.encode("utf-8")
        shape_text = ",".join(str(x) for x in tensor.shape).encode("ascii")
        dtype_text = dtype_name(tensor).encode("ascii")
        for value in (key_bytes, shape_text, dtype_text):
            digest.update(len(value).to_bytes(8, "big"))
            digest.update(value)
        digest.update(tensor.view(torch.uint8).numpy().tobytes())
    return digest.hexdigest()


def axis(value, rank, insertion=False):
    lower = -(rank + 1) if insertion else -rank
    upper = rank if insertion else rank - 1
    if value < lower or value > upper:
        raise ConversionError(f"axis {value} is out of range for rank {rank}")
    return value + rank + (1 if insertion else 0) if value < 0 else value


def interleave(tensor, dim, groups, sizes, reverse=False):
    dim = axis(dim, tensor.ndim)
    if groups <= 0 or sum(sizes) != tensor.shape[dim] or any(size % groups for size in sizes):
        raise ConversionError("invalid interleave dimensions")
    if reverse:
        per_group = [size // groups for size in sizes]
        chunks = torch.split(tensor, per_group * groups, dim=dim)
        ordered = [chunks[group * len(sizes) + segment] for segment in range(len(sizes)) for group in range(groups)]
    else:
        segments = torch.split(tensor, sizes, dim=dim)
        chunks = [torch.chunk(segment, groups, dim=dim) for segment in segments]
        ordered = [chunks[segment][group] for group in range(groups) for segment in range(len(sizes))]
    return torch.cat(ordered, dim=dim)


def evaluate(expr, sources, depth=0):
    if depth > 64 or not isinstance(expr, dict) or not isinstance(expr.get("op"), str):
        raise ConversionError("invalid or over-deep transform expression")
    op = expr["op"]
    if op == "source":
        return sources[expr["key"]]
    if op in {"identity", "alias"}:
        return evaluate(expr["input"], sources, depth + 1)
    if op in {"concat", "stack"}:
        items = [evaluate(item, sources, depth + 1) for item in expr["inputs"]]
        return torch.cat(items, dim=expr["axis"]) if op == "concat" else torch.stack(items, dim=expr["axis"])
    value = evaluate(expr["input"], sources, depth + 1)
    if op == "reshape":
        return value.reshape(tuple(expr["shape"]))
    if op == "permute":
        return value.permute(tuple(expr["axes"]))
    if op == "transpose":
        return value.transpose(*expr["axes"])
    if op == "slice":
        dim = axis(expr["axis"], value.ndim)
        selection = [slice(None)] * value.ndim
        selection[dim] = slice(expr["start"], expr["stop"], expr.get("step", 1))
        return value[tuple(selection)]
    if op == "squeeze":
        return value.squeeze(expr["axis"])
    if op == "unsqueeze":
        return value.unsqueeze(expr["axis"])
    if op == "interleave":
        return interleave(value, expr["axis"], expr["groups"], expr["segment_sizes"])
    if op == "deinterleave":
        return interleave(value, expr["axis"], expr["groups"], expr["segment_sizes"], True)
    raise ConversionError(f"unknown transform operation {op!r}")


def dependencies(expr):
    if expr["op"] == "source":
        return {expr["key"]}
    if "input" in expr:
        return dependencies(expr["input"])
    if "inputs" in expr:
        return set().union(*(dependencies(item) for item in expr["inputs"]))
    return set()


def parse_size(text):
    text = text.strip().upper().replace("IB", "B")
    for suffix, multiplier in (("GB", 1024**3), ("MB", 1024**2), ("KB", 1024), ("B", 1)):
        if text.endswith(suffix):
            result = int(float(text[:-len(suffix)].strip()) * multiplier)
            if result > 0:
                return result
    raise ConversionError(f"invalid positive byte size {text!r}")


def shard_groups(max_bytes):
    groups = []
    current = []
    used = 0
    for key, target in sorted(PLAN["targets"].items()):
        elements = 1
        for size in target["shape"]:
            elements *= size
        item_bytes = elements * torch.tensor([], dtype=getattr(torch, target["dtype"])).element_size()
        if current and used + item_bytes > max_bytes:
            groups.append(current)
            current, used = [], 0
        current.append(key)
        used += item_bytes
    if current:
        groups.append(current)
    return groups


def convert(source_path, output, max_shard_size):
    source_path = Path(source_path).resolve(strict=True)
    output = Path(output).resolve(strict=False)
    if output == source_path:
        raise ConversionError("output must not overwrite the input checkpoint")
    if output.exists() and (output.is_file() or any(output.iterdir())):
        raise ConversionError(f"refusing to replace non-empty output {output}")
    store = Store(source_path)
    expected_keys = set(PLAN["source_tensors"])
    if set(store.keys()) != expected_keys:
        raise ConversionError("source checkpoint keys do not match the embedded plan")
    for key, expected in PLAN["source_tensors"].items():
        actual = metadata(store.read(key))
        if actual != (tuple(expected["shape"]), expected["dtype"]):
            raise ConversionError(f"source tensor {key!r} metadata does not match the plan")
    actual_fingerprint = fingerprint(store)
    if actual_fingerprint != PLAN["source"]["checkpoint_fingerprint"]:
        raise ConversionError("source checkpoint fingerprint does not match the embedded plan")
    groups = shard_groups(max_shard_size)
    output_is_file = output.suffix == ".safetensors"
    if output_is_file and len(groups) != 1:
        raise ConversionError("single-file output exceeds max shard size")
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix=f".{output.stem}.neuralabi-", dir=output.parent))
    bundle = temporary / "bundle"
    bundle.mkdir()
    weight_map = {}
    try:
        for index, keys in enumerate(groups, 1):
            values = {}
            for key in keys:
                target = PLAN["targets"][key]
                needed = {name: store.read(name) for name in sorted(dependencies(target["expression"]))}
                tensor = evaluate(target["expression"], needed).detach().cpu().contiguous().clone()
                if metadata(tensor) != (tuple(target["shape"]), target["dtype"]):
                    raise ConversionError(f"generated target tensor {key!r} has wrong metadata")
                values[key] = tensor
            filename = "model.safetensors" if len(groups) == 1 else f"model-{index:05d}-of-{len(groups):05d}.safetensors"
            save_file(dict(sorted(values.items())), bundle / filename, metadata={"neuralabi": "0.1"})
            weight_map.update({key: filename for key in keys})
        if len(groups) > 1:
            total_size = 0
            for target in PLAN["targets"].values():
                elements = 1
                for size in target["shape"]:
                    elements *= size
                total_size += elements * torch.tensor([], dtype=getattr(torch, target["dtype"])).element_size()
            index = {"metadata": {"total_size": total_size}, "weight_map": dict(sorted(weight_map.items()))}
            (bundle / "model.safetensors.index.json").write_text(json.dumps(index, sort_keys=True, indent=2) + "\n", encoding="utf-8")
        if output_is_file:
            os.replace(bundle / "model.safetensors", output)
            shutil.rmtree(temporary, ignore_errors=True)
        else:
            if output.exists():
                output.rmdir()
            os.replace(bundle, output)
            shutil.rmtree(temporary, ignore_errors=True)
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise


def main():
    parser = argparse.ArgumentParser(description="Standalone NeuralABI checkpoint converter")
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--max-shard-size", default="2GB")
    args = parser.parse_args()
    try:
        convert(args.source, args.output, parse_size(args.max_shard_size))
    except (ConversionError, OSError, RuntimeError, ValueError) as exc:
        parser.exit(2, f"converter: error: {exc}\n")
    print(f"Converted with plan __PLAN_HASH__ to {args.output}")


if __name__ == "__main__":
    main()
'''


def render_converter(plan: ConversionPlan) -> str:
    validate_plan(plan)
    plan_json = canonical_dumps(plan.to_dict())
    literal = repr(plan_json)
    return (
        _TEMPLATE.replace("__TOOL_VERSION__", plan.tool_version)
        .replace("__PLAN_HASH__", plan.plan_hash)
        .replace("__SOURCE_GRAPH_HASH__", plan.source.graph_hash)
        .replace("__TARGET_GRAPH_HASH__", plan.target.graph_hash)
        .replace("__PLAN_JSON_LITERAL__", literal)
    )


def emit_converter(plan: ConversionPlan, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_converter(plan), encoding="utf-8", newline="\n")
